services:
  - type: web
    name: ci-cd-back
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    rootDir: ./backend
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: false
      - key: BCRYPT_ROUNDS
        value: false
      - key: PORT
        value: false
      - key: NODE_ENV
        value: false
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_INITDB_ROOT_USERNAME
        sync: false
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false
      - key: MONGO_INITDB_DATABASE
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false