name: Build, Test and Deploy Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and test
        run: |
          npm ci
          npm test

  deploy_to_render:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true

  trigger-frontend:
    runs-on: ubuntu-latest
    needs: deploy_to_render
    steps:
      - name: Trigger frontend workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/Jamil18474/ci-cd-react/dispatches \
            -d '{"event_type":"dispatch-event"}'